# Generated by Django 5.2.6 on 2025-10-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_tags_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='posts',
            name='posts_posts_time_cr_96f207_idx',
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['-time_created'], name='posts_posts_time_cr_2a954a_idx'),
        ),
    ]
