# Generated by Django 5.2.6 on 2025-11-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_posts_author_like_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления'),
        ),
    ]
