# Generated by Django 5.2.6 on 2026-02-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='test_value', max_length=100, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
